### PR TITLE
[FEAT]  Dockerfile to the project

### PR DESCRIPTION
**Pull request by rivo2302**
- [ADD] Dockerfile [#2](https://github.com/rivo2302/MozItaReBot/commit/208c3c4f6f7e9b4af88b41113c1864b04d1c4f5f)

### CODE REVIEW

**Comment by dag7dev** [comment]
Thanks for your contribution! Could you please think about running the tests included in the tests folder?

Also, did you tested the machine?

**Review by dag7dev — COMMENTED** [review]
this doesn't sound like a breaking change, why did you moved row 105 to row 112?

**Comment by rivo2302** [comment]
> this doesn't sound like a breaking change, why did you moved row 105 to row 112?

 @dag7dev  You are right I have revert the commit for this

**Comment by rivo2302** [comment]
Ye

> Thanks for your contribution! Could you please think about running the tests included in the tests folder?
> 
> Also, did you tested the machine?

@dag7dev  Yes, I thought about it. But I haven't had time to finish it yet.
I'll work on it again as soon as I'm available.

Can  you accept  my PR?

**Comment by Trafitto** [comment]
Currently there is no need for Docker, we thank you for your contribution but I think the pr should be rejected

**Pull request closed without merging**
